[versions]
fabric-api = "0.100.3+1.21"
fabric-kotlin = "1.11.0+kotlin.2.0.0"
fabric-loader = "0.15.11"
fabric-loom = "1.7-SNAPSHOT"
fabric-mappings = "1.21+build.2"
kotlin = "2.0.0"
kotlin-logging = "6.0.9"
minecraft = "1.21"

[libraries]
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-mappings = { group = "net.fabricmc", name = "yarn", version.ref = "fabric-mappings" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }
minecraft = { group = "org.mojang", name = "minecraft", version.ref = "minecraft" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
loom = { id = "fabric-loom", version.ref = "fabric-loom" }